/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CcnButtonSlide {
    'direction': string;
  }
  interface CcnButtonSlideAttributes extends StencilHTMLAttributes {
    'direction'?: string;
  }

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CcnButtonSlide': Components.CcnButtonSlide;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'ccn-button-slide': Components.CcnButtonSlideAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLCcnButtonSlideElement extends Components.CcnButtonSlide, HTMLStencilElement {}
  var HTMLCcnButtonSlideElement: {
    prototype: HTMLCcnButtonSlideElement;
    new (): HTMLCcnButtonSlideElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'ccn-button-slide': HTMLCcnButtonSlideElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'ccn-button-slide': HTMLCcnButtonSlideElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
