/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MeButton {
    'direction': string;
  }
  interface MeButtonAttributes extends StencilHTMLAttributes {
    'direction'?: string;
  }

  interface MyComponent {
    'first': string;
    'last': string;
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MeButton': Components.MeButton;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'me-button': Components.MeButtonAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLMeButtonElement extends Components.MeButton, HTMLStencilElement {}
  var HTMLMeButtonElement: {
    prototype: HTMLMeButtonElement;
    new (): HTMLMeButtonElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'me-button': HTMLMeButtonElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'me-button': HTMLMeButtonElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
